[project]
name = "polyester"
version = "0.2.3"
description = "Run R interpreter from python"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "narwhals>=2.16.0",
    "pyarrow>=23.0.1",
    "tstr; python_version < '3.14'"
]
license = "Apache-2.0"
keywords = ["interoperability", "R", "statistics", "remote-interpreter"]
classifiers = [
    "Intended Audience :: Developers",
    "Intended Audience :: Science/Research",
    "Topic :: Scientific/Engineering",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "Operating System :: OS Independent",
]
# Here all workers will need to be included
[tool.setuptools.package-data]
polyester = [
    "workers/*.R"
]

[tool.pytest]
pythonpath = ["src"]

[dependency-groups]
dev = [
    "pytest>=9.1.1",
]

[project.urls]
Homepage = "https://github.com/lverweijen/polyester"
Repository = "https://github.com/lverweijen/polyester"
Issues = "https://github.com/lverweijen/polyester/issues"
Changelog = "https://github.com/lverweijen/polyester/blob/main/CHANGELOG.md"
